name: Flex 3.20 Dockers Build

# This workflow builds the OpenEMR Flex Docker images with Alpine 3.20 and PHP versions 8.2, and 8.3.
# And in this configuration will create following dockers (and tags):
#    PHP 8.2: openemr/openemr:flex-3.20-php-8.2
#    PHP 8.3: openemr/openemr:flex-3.20-php-8.3, openemr/openemr:flex-3.20
#
# php_versions is a JSON array of PHP versions to build.
#
# The php_default will determine the default PHP version (ie. above tag without a php version).
#
# The is_default_flex environment variable is used to determine if this is the default flex image.
#  (This is NOT the default flex image, so is_default_flex is false)

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-flex-core.yml
    with:
      is_default_flex: false
      alpine_version: "3.20"
      php_versions: '["8.2", "8.3"]'
      php_default: "8.3"
    secrets: inherit
