name: Flex 3.22 Dockers Build

# This workflow builds the OpenEMR Flex Docker images with Alpine 3.22 and PHP versions 8.2, 8.3, and 8.4.
# And in this configuration will create following dockers (and tags):
#    PHP 8.2: openemr/openemr:flex-3.22-php-8.2
#    PHP 8.3: openemr/openemr:flex-3.22-php-8.3
#    PHP 8.4: openemr/openemr:flex-3.22-php-8.4, openemr/openemr:flex-3.22, openemr/openemr:flex
#
# php_versions is a JSON array of PHP versions to build.
#
# The php_default will determine the default PHP version (ie. above tag without a php version).
#
# The is_default_flex environment variable is used to determine if this is the default flex image.
#
# THIS ALPINE 3.22 VERSION IS TAGGED AS openemr/openemr:flex (THE DEFAULT FLEX IMAGE SINCE is_default_flex IS TRUE)
# (ENSURE TO MAKE THIS (is_default_flex) FALSE WHEN A NEW ALPINE VERSION TAKES OVER AS THE DEFAULT!)

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-flex-core.yml
    with:
      is_default_flex: true
      alpine_version: "3.22"
      php_versions: '["8.2", "8.3", "8.4"]'
      php_default: "8.4"
    secrets: inherit
