# This will run the OpenEMR flex dockers with Alpine Edge version. It will test the flex docker images in both
#  development (ie. dev) mode (codebase used from a shared volume) and production (ie. prod) mode (codebase collected via git).
#  - is_production_docker is required and needs to be false.
#  - alpine_versions is set to edge
#  - php_versions are set to 8.2, 8.3, and 8.4
#  - is_flex_coverage_docker is set to true (so coverage will be collected in both dev mode and prod mode dockers)
#  - flex_coverage_php_version is set to 8.4 (this is the docker's php versions to use for coverage collection)

name: OpenEMR Flex Edge Docker Test

on:
  push:
    branches:
    - master
    paths:
    - '.github/workflows/test-flex-edge.yml'
    - 'docker/openemr/flex/**'
    - '.github/actions/test-actions-core/action.yml'
    - '.github/workflows/test-core.yml'
  pull_request:
    branches:
    - master
    paths:
    - '.github/workflows/test-flex-edge.yml'
    - 'docker/openemr/flex/**'
    - '.github/actions/test-actions-core/action.yml'
    - '.github/workflows/test-core.yml'

jobs:
  build:
    uses: ./.github/workflows/test-core.yml
    with:
      is_production_docker: false
      alpine_version: "edge"
      php_versions: '["8.2", "8.3", "8.4"]'
      is_flex_coverage_docker: true
      flex_coverage_php_version: '8.4'
