# This will run the OpenEMR flex dockers with Alpine 3.22 version. It will test the flex docker images in both
#  development (ie. dev) mode (codebase used from a shared volume) and production (ie. prod) mode (codebase collected via git).
#  - is_production_docker is required and needs to be false.
#  - alpine_versions is set to 3.22
#  - php_versions are set to 8.2, 8.3, and 8.4
#  - note not using the coverage settings (is_flex_coverage_docker, flex_coverage_php_version) in this workflow. see
#    test-flex-edge.yml for use of these settings.

name: OpenEMR Flex 3.22 Docker Test

on:
  push:
    branches:
    - master
    paths:
    - '.github/workflows/test-flex-322.yml'
    - 'docker/openemr/flex/**'
    - '.github/actions/test-actions-core/action.yml'
    - '.github/workflows/test-core.yml'
  pull_request:
    branches:
    - master
    paths:
    - '.github/workflows/test-flex-322.yml'
    - 'docker/openemr/flex/**'
    - '.github/actions/test-actions-core/action.yml'
    - '.github/workflows/test-core.yml'

jobs:
  build:
    uses: ./.github/workflows/test-core.yml
    with:
      is_production_docker: false
      alpine_version: "3.22"
      php_versions: '["8.2", "8.3", "8.4"]'
